version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: diet_db
    volumes:
      - ./database/schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app